name: CI/CD Pipeline for Cross-Platform Checks

on:
  push:
    branches:
      - master
    paths:
      - 'squadds/**'
  workflow_dispatch:

jobs:
  cross-platform-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.os == 'Windows' && '~\AppData\Local\pip\Cache' || '' }}
            ${{ runner.os == 'macOS' && '~/Library/Caches/pip' || '' }}
            ${{ runner.os == 'Linux' && '~/.cache/pip' || '' }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pip
          pip install datasets
          pip install pyEPR-quantum
          pip install pyaedt
          pip install -r requirements.txt
          pip install qiskit-metal
          pip install -e .

      - name: Run Tests
        run: |
          python tests/imports_test.py
