name: Build and Test

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install datasets
          pip install pyEPR-quantum
          pip install pyaedt
          pip install -e . 
          pip install -r requirements.txt

      - name: Verify qutip and scqubits Installation
        run: |
          python -c "import qutip; print(qutip.__version__)"
          python -c "import scqubits; print(scqubits.__version__)"

      - name: Test Python Imports
        run: python imports_test.py

      - name: Install documentation dependencies
        run: |
          pip install sphinx qiskit-sphinx-theme nbsphinx jupyter_sphinx sphinx_copybutton sphinx_design reno sphinxcontrib-katex pydata_sphinx_theme recommonmark

      - name: Install Pandoc v 2.18
        run: |
          sudo apt-get remove -y pandoc
          wget https://github.com/jgm/pandoc/releases/download/2.18/pandoc-2.18-1-amd64.deb
          sudo dpkg -i pandoc-2.18-1-amd64.deb

      - name: List files
        run: ls -lah
