name: CI/CD Pipeline for Cross-Platform Checks

on:
  push:
    branches:
      - master
    paths:
      - 'squadds/**'
  workflow_dispatch:

jobs:
  cross-platform-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download environment.yml from Qiskit-Metal repository
        run: curl -O https://raw.githubusercontent.com/Qiskit/qiskit-metal/main/environment.yml

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false

      - name: Remove existing Conda environment if it exists
        shell: bash -l {0}
        run: |
          conda remove --name qiskit-metal-env --all --yes || true

      - name: Create and Activate Qiskit-Metal Conda environment
        shell: bash -l {0}
        run: |
          conda env create -n qiskit-metal-env -f environment.yml
          echo "conda activate qiskit-metal-env" >> $BASH_ENV

      - name: Install Qiskit-Metal
        shell: bash -l {0}
        run: |
          python -m pip install --no-deps -e git+https://github.com/Qiskit/qiskit-metal.git#egg=qiskit-metal

      - name: Install SQuADDS and its dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install datasets
          pip install pyEPR-quantum
          pip install pyaedt
          pip install -r requirements.txt
          pip install -e .

      - name: Run Tests
        shell: bash -l {0}
        run: |
          python tests/imports_test.py
